language: node_js

node_js:
  - "stable"

cache: npm

install:
  - npm install

before_script:
  - npm ci
script:
  - CI=false npm run build:production

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master